### ISSUE TITLE
Never Encounter Certain Pokemon

### ISSUE THREAD

**Issue by LeviLewinsky** [Unlucky-Life/ankimon#157]
I've noticed that even if I set up the system to only give me Generation 1 Pokemon, I've still never encountered certain pokemon: Pikachu, Bulbasaur/Ivysaur/Venusaur, Charmander/Charmeleon/Charizard, and Squirtle/Wartortle/Blastoise. Is there a reason these particular pokemon seem so rare? I've already seen like 50 Mews and Mewtwos, which I would definitely consider to be more "rare", as well as many, many Articunos/Zapdos/Moltres. Is this just an RNG situation where I just happen to have not seen these pokemon, or are they not in the code for regular encounters?

**Comment by Unlucky-Life** [comment]
Hi @LeviLewinsky !
So i dont know why you wont encounter pikachu but you cant encounter the starters ! (Thats due to me wanting to integrate certain events to receive more starters).

2. Every Anki start is counted as one "one review session" and with every review your chances to see a legendary or mythical pokemon rises.

**Comment by Unlucky-Life** [comment]
But Im reworking the chances of encounter newly !
