### ISSUE TITLE
No Sound

### ISSUE THREAD

**Issue by crabman4** [Unlucky-Life/ankimon#181]
Hello! The add on is working great! the only thing is there is no sound. Is there suppose to be no sound?

**Comment by Unlucky-Life** [comment]
Hi  @crabman4,
Ankimon can have sound if you like it to ! Just go to the settings and set the needed / wanted sounds to true. (For some mac devices sadly sounds dont work due to some sound libraries not running on them - For an unknown reason.)
I hope that helps !
Let me know if it does / does not !
Sincerly, Unlucky 🪨

**Comment by crabman4** [comment]
Hey! I turned all of the sound settings to true, and now I can hear the
sounds of the pokemon when I am in battle. I don't hear any other sounds,
but I am on a Mac. Are there suppose to be other sounds?

- Chandler Wrege

**Comment by Unlucky-Life** [comment]
@crabman4 Which version are you currently using ? (The latest from AnkiWeb or here from GitHub) ?
There are sounds for dealing dmg (effective, super effective, etc)
and Pokemon Battle Cries
(The Addon uses a python library for sounds also used by other addons)
