### ISSUE TITLE
Can't see battle on Card Screen

### ISSUE THREAD

**Issue by ayshapatel7** [Unlucky-Life/ankimon#192]
I can't see the attack stat or bar at the bottom of my anki cards, I've seen that it shows up on my friends accounts though. How can I fix that? I've deleted and redownloaded like 4 times now. The ankimon extra window seems to work fine.

**Comment by Unlucky-Life** [comment]
@ayshapatel7 Is it only the bar at the bottom or the complete styling ?
Ankimon tries to inject HTML Code into the Reviewer to show you ur styling - this might be influenced by the type of card styling u are using. Could you make a screenshot and send it here ?

**Comment by ayshapatel7** [comment]
<img width="1470" alt="Screenshot 2024-09-11 at 4 06 15 PM" src="https://github.com/user-attachments/assets/98dc1a33-c47a-4adb-be6f-c7668b15f3f5">

I have attached the image here. As you can see there is only the blurb on what attack my pokemon is using, but there is not the image of the pokemon or the attack bar. I am using the Anking deck for STEP 1 studying.

**Comment by Unlucky-Life** [comment]
@ayshapatel7 Ok thats weird - can you check in the settings - under Addons => for styling in reviewer ? I can imagine it could also be due to a collision with the Background Customization addon you are using. Which specific Addons are you using and could you test the Addon on a "test" card deck (just a basic card type).

**Comment by ayshapatel7** [comment]
I have no idea why, but it started working all of a sudden. Thanks for looking into it!
