### ISSUE TITLE
After wild Pokemon takes damage (shakes), it shoots off to the right

### ISSUE THREAD

**Issue by Gameshoww** [Unlucky-Life/ankimon#195]
On Mac -- After a wild Pokemon takes damage, the wild Pokemon preview in the "Anki Cards" window will shake (normal) but then shoot off to the right before reseting. Video attached.

https://github.com/user-attachments/assets/1cc68f98-8175-4eca-b6ae-b951007855ba

**Comment by Unlucky-Life** [comment]
thx for letting me know !
@Gameshoww This might happen due to the styling from the Custom Background Addon or Cards that can influence the addon - but i can also imagine it might be due to the Ankimon Code aswell. Do you have any coding experience by chance, then I could let you know where to change it :)

**Comment by Unlucky-Life** [comment]
@Gameshoww Ok so this could be a little complicated, cause I believe you would need to play around with the code a little.

**Comment by Unlucky-Life** [comment]
![image](https://github.com/user-attachments/assets/f9c1a9e8-b2d1-4e42-9f35-618e07f6be05)
^this is the part you need to edit - here the following steps:
Install VS Code:

If you don't already have Visual Studio Code installed, [download it here](https://code.visualstudio.com/Download) and install it.
Open VS Code:

Launch Visual Studio Code from your Start menu or by running code from the terminal (if you added it to the PATH).
Open the Python File:

In VS Code, click on File > Open File... and navigate to the Python file you want to edit.
You can also drag and drop the Python file directly into the VS Code window.
Navigate to Line 4990:

Press Ctrl + G or Cmd + G (on macOS), and a "Go to Line" prompt will appear.
Type 4990 and press Enter to go directly to line 4990.
Edit the Code:

On line 4990, you can make your changes.
For your specific change, update the @keyframes shake code so that the last transform (the one at 100%) becomes translateX(0vw).



Save the Changes:
Press Ctrl + S (or Cmd + S on macOS) to save the file.

**Comment by Unlucky-Life** [comment]
@keyframes shake {{
                0% {{ transform: translateX(0) rotateZ(0); filter: drop-shadow(0 0 10px rgba(255, 0, 0, 0.5)); }}
                10% {{ transform: translateX(-10%) rotateZ(-5deg); }}
                20% {{ transform: translateX(10%) rotateZ(5deg); }}
                30% {{ transform: translateX(-10%) rotateZ(-5deg); }}
                40% {{ transform: translateX(10%) rotateZ(5deg); }}
                50% {{ transform: translateX(-10%) rotateZ(-5deg); }}
                60% {{ transform: translateX(10%) rotateZ(5deg); }}
                70% {{ transform: translateX(-10%) rotateZ(-5deg); }}
                80% {{ transform: translateX(10%) rotateZ(5deg); }}
                90% {{ transform: translateX(-10%) rotateZ(-5deg); }}
                100% {{ transform: translateX(0vw); filter: drop-shadow(0 0 10px rgba(255, 0, 0, 0.5)); }}
            }}


^the shake part should then look something like this

**Comment by Johnnym3334** [comment]
Hey, I just wanted to say that I was also having this issue but on a Windows 11 device. I ended up making the edit on the file you suggested and it made the pokemon "shooting away" issue get fixed! So it works normally now :)
