### ISSUE TITLE
XP Bar after Level Up 0

### ISSUE THREAD

**Issue by nurkittel** [Unlucky-Life/ankimon#37]
Hi,

I don't know if it's supposed to be like that but every time my Pokemon reached a new level my XP-Bar was 0 and the EXP from the previous fight did not transfer to the new level. See screenshots.

<img width="1440" alt="Screenshot 2024-03-24 at 12 29 49" src="https://github.com/Unlucky-Life/ankimon/assets/83577787/477750d3-cb95-443b-8f9c-2ab2af223390">
<img width="1440" alt="Screenshot 2024-03-24 at 12 31 39" src="https://github.com/Unlucky-Life/ankimon/assets/83577787/cbcda917-0888-4359-99eb-5067243e73be">

**Comment by Unlucky-Life** [comment]
Yes this is correct. Basically => If your pokemon gets enough XP - more then needed for the next lvl => it reaches the next level and xp is set to 0.

I may need to re-do the logic in the future and correctly calculate the xp.

**Comment by omfgroflmfaol** [comment]
not sure if you fixed it already and haven't put it into the change notes for 1.27 but I looked at the function `save_main_pokemon_progress` and the issue lies with the line `mainpokemon_xp = 0`. This can be easily fixed by changing it to:
`mainpokemon_xp = int(mainpokemon_xp) - int(experience)`

With this change, you will only level up once per fight, even if you have enough exp to level up more than once. This should occur rather seldomly, but it can also be easily fixed by changing the levelup event listener (`if int(experience) < int(mainpokemon_xp) and mainpokemon_level != 100`) to a **while** loop (the corresponding `else` can be left as is):
`while int(experience) < int(mainpokemon_xp) and mainpokemon_level != 100`
(...)
`else`
`     msg = ""`
`     msg += f"Your {mainpokemon_name} has gained {exp} XP.\n {experience} exp is needed for next level \n Your pokemon currently has {mainpokemon_xp}"`
(...)

Tested it and it works 👍 

Note that the part within `else` is only executed when the `while` loop terminates naturally (by its condition becoming false), but not if you at some point decided to add a `break` command somewhere in the `while` loop.
