### ISSUE TITLE
Pokemon error when using "Low sweep"

### ISSUE THREAD

**Issue by h0zierfan** [Unlucky-Life/ankimon#49]
"An error occured in reviewer: unsupported operand type(s) for -=: 'int' and 'NoneType'" occurs once I reteach my machop low sweep, and the move is chosen.

**Comment by Unlucky-Life** [comment]
ok thanks for the notice ! could you send me your mainpokemon.json file to test this but out myself ?
Thx for adding the notice !

**Comment by h0zierfan** [comment]
this is the only time I've experienced the error, and this only occurred after I "remembered" low kick

**Comment by Unlucky-Life** [comment]
hm i see - then this error seems to be due to the move itself ! Thanks for the infos !

**Comment by Unlucky-Life** [comment]
@h0zierfan so i havetested it again - and your correct its due to the move low kick - some moves somehow create issues or maybe dont have a proper effect yet - ill try to fix this if possible.
For now i recommend to remove thos attacks by using the remember attack button and replacing low kick with a different attack
