### ISSUE TITLE
Encountering similar pokemon

### ISSUE THREAD

**Issue by h0zierfan** [Unlucky-Life/ankimon#55]
(Love the add-on so far btw, amazing job!)

Have been using the add-on the last few days pretty consistently, and am starting to notice a lot of the same pokemon have been appearing for me -- most of the ultra beasts I have seen 5-10 times each -- and I have encountered a lot of the baby pokemon like smoochum (3 in a row one time), igglybuff, and budew. Sometimes I get a random pokemon it seems, but it seems odd that the same pokemon have been popping up when the pool is hypothetically so large. Is there a method that the encounters are calculated? Or is it intentionally not meant to be that random. 

Thank you!

**Comment by Unlucky-Life** [comment]
Hm that sounds weird with the same 3 pokemons but this is due to multiple things:
the pokemon you encounter are based off of how many cards you are doing in that review.
Meaning: 
at a card counter smaller than 80 => normal pokemon appear
at a card counter between 80 - 100 => baby pokemon and normal pokemon appear
at a card counter between 80 - 130  => Ultra, baby and normal pokemon can appear
at a card count between 130 - 180 => legendary, ultra, baby and normal pokemon can appear
at a card count of later than 180 => mythical, legendary, ultra, baby and normal pokemon can appear
-- These randomly generated pokemon tiers are based chance => propably the error is in my code that the chance right now of baby pokemon appearing is a little to high to normal pokemon 
--- the amount of baby pokemon to normal pokemon is also an issue here.
=> aswell as the following:
pokemon can only be generated if their evolution level is greater than their randomly generated level.
Meaning => a metapod will only appear at level 7 or greater

**Comment by Unlucky-Life** [comment]
everytime you see a card a card_counter goes up by 1

**Comment by h0zierfan** [comment]
Very interesting! Thank you for clearing it up -- I think I haven't reset my anki in a while, so that may explain why I've gotten a lotttt of ultra beast pokemon.
